spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://none:3306/railway}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:test}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 120000
      idle-timeout: 120000
      connection-timeout: 120000
      leak-detection-threshold: 120000 

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    locale: es_CO
    time-zone: America/Bogota
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
      
server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger UI custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /api-docs
  packages-to-scan: com.test.accenture.backend.interfaces.controller
