spring:
  datasource:
    url: jdbc:mysql://metro.proxy.rlwy.net:28851/railway
    username: root
    password: EfpVWgYHnPiMnZcVhKtkKJpSBKjezaDG
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 120000
      idle-timeout: 120000
      connection-timeout: 120000
      leak-detection-threshold: 120000 

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  r2dbc:
    url: r2dbc:mysql://root:EfpVWgYHnPiMnZcVhKtkKJpSBKjezaDG@metro.proxy.rlwy.net:28851/railway?ssl=false

  jackson:
    locale: es_CO
    time-zone: America/Bogota
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
      
server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
