apiVersion: v1
kind: Service
metadata:
  name: test-accenture-backend
  labels:
    app: test-accenture-backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: test-accenture-backend 